In [6]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


In [11]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr_2d)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [12]:
arr_2d.ndim

2

In [13]:
arr_2d.size

10

In [14]:
arr_2d.shape

(2, 5)

In [15]:
#(row,colnm)

In [16]:
arr_2d.dtype

dtype('int64')