In [1]:
import numpy as np

In [2]:
arr_3d = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(arr_3d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
arr_3d = np.ones(7)
print(arr_3d)

[1. 1. 1. 1. 1. 1. 1.]


In [5]:
arr_3d.dtype

dtype('float64')

In [6]:
arr_3d = np.ones((4,4),dtype=int)
print(arr_3d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
arr_3d = np.ones((4,4),dtype=bool)
print(arr_3d)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [7]:
arr_3d.dtype

dtype('int64')

In [9]:
arr_3d = np.zeros((3,4),dtype=int)
print(arr_3d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
arr_3d = np.zeros((3,4),dtype=bool)
print(arr_3d)

[[False False False False]
 [False False False False]
 [False False False False]]


In [11]:
arr_3d = np.zeros((3,4),dtype=str)
print(arr_3d)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [1]:
arr_3d = np.empty((2,2),dtype=int)
print(arr_3d)

NameError: name 'np' is not defined