<h2>Numpy Function</h2>

In [3]:
import numpy as np

<h2>Arange Function</h2>

In [14]:
#arange(start,end,steps)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
even_1d = np.arange(0,13,2)
print(even_1d)

[ 0  2  4  6  8 10 12]


<h2>linespace()</h2>

In [10]:
arr1_1d = np.linspace(1,5,4)
print(arr_1d)

[1.         2.33333333 3.66666667 5.        ]


<h2>reshape()</h2>

In [16]:
ar_2d = arr_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
ar_3d = arr_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


<h2>ravel()</h2>

In [19]:
#2d to 1d
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

<h2>flatten()</h2>

In [20]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

<h2>transpose()</h2>

In [21]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [22]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])