<h2>Methimatical operation using numpy</h2>

In [1]:
import numpy as np

In [2]:
ar1 = np.arange(1,10).reshape(3,3)
ar2 = np.arange(1,10).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
ar1+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(ar1,ar2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
np.subtract(ar1,ar2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
#multiplication element to element
np.multiply(ar1,ar2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [7]:
np.divide(ar1,ar2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ar1@ar2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [9]:
ar1.dot(ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [10]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#maximum value of the matrix
ar1.max()

np.int64(9)

In [14]:
#indix of maximum value
ar1.argmax()

np.int64(8)

In [16]:
#maximum value of the every row
ar1.max(axis = 0)

array([7, 8, 9])

In [17]:
#maximum value of the every colum
ar1.max(axis = 1)

array([3, 6, 9])

In [19]:
#same for minimum values use min

In [21]:
#sum of all values
np.sum(ar1)

np.int64(45)

In [22]:
#sum values of row
np.sum(ar1,axis = 0)

array([12, 15, 18])

In [23]:
#average of array
np.mean(ar1)

np.float64(5.0)

In [24]:
#squre root of every value
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])